### ISSUE TITLE
Why does the Builder only accept strings? 

### ISSUE THREAD

**Issue by Coccodrillo** [BullyBoo/Encryption#1]
HI Rostislav,

I like the project and think it's quite useful and your design patterns seem nice, but there was a question I was asking myself. 

Maybe I am missing something, but why did you choose to only accept strings instead of byte arrays? It would make this lib convenient for encrypting other pieces of data as well.

**Comment by BullyBoo** [comment]
Hi 
You also can set data as byte array. But this function is supported only for encryption keys and initialization vectors.
However the messages can only be set as String. I will try to change it soon.

**Comment by BullyBoo** [comment]
Hi, with version 1.0.1 the method message accepts :
byte[]
short
short[]
int
int[]
float
float[]
long
long[]
double
double[]
String
