### ISSUE TITLE
Decryption returns null response

### ISSUE THREAD

**Issue by kmvora13990** [BullyBoo/Encryption#3]
This is my code..please check..
 public String decrypt(String text)
    {
        try
        {
            String decode = String.valueOf(Base64.decode(text,Base64.DEFAULT));

            String temp = decode;
            temp = temp.replaceAll("-","+");
            String decoded = URLDecoder.decode(temp, "UTF-8");

            decryptText = Encoder.BuilderAES()
                    .message(decoded)
                    .method(AES.Method.AES_ECB_PKCS7PADDING)
                    .key(App.ENCRYPT_DECRYPT_KEY)
                    .keySize(AES.Key.SIZE_128)
                    .iVector("")
                    .decrypt();
            return decryptText;
        }catch(Exception e)
        {Log.d("came decrypt ex","" + e);
            e.printStackTrace();
            return "";
        }

    }

**Comment by BullyBoo** [comment]
what is your jdk version?

**Comment by kmvora13990** [comment]
My JDK version is jdk1.8.0_111

**Comment by BullyBoo** [comment]
Is it android or java project?

**Comment by kmvora13990** [comment]
Android

**Comment by BullyBoo** [comment]
I think that ur decode message is not valid. I`m repeating this cipher method now. My message was succesfully encrypt and decrypt.
Also, if u are using ECB mode, u can do not set the initialization vector, because it is not using in this mode.

If u want, u can give me ur message and key, and i will try to repeat it again.

**Comment by kmvora13990** [comment]
I have check it in online tools, its decrypting well. but in library its always returns me null .

**Comment by BullyBoo** [comment]
I'm sorry, but i can't help u, if will not get more information.
Maybe you can show your exception?

**Comment by kmvora13990** [comment]
08-30 18:31:16.711 4233-4233/? W/System.err: javax.crypto.IllegalBlockSizeException: error:1e00007b:Cipher functions:OPENSSL_internal:WRONG_FINAL_BLOCK_LENGTH
08-30 18:31:16.711 4233-4233/? W/System.err:     at com.android.org.conscrypt.NativeCrypto.EVP_CipherFinal_ex(Native Method)
08-30 18:31:16.711 4233-4233/? W/System.err:     at com.android.org.conscrypt.OpenSSLCipher$EVP_CIPHER.doFinalInternal(OpenSSLCipher.java:568)
08-30 18:31:16.711 4233-4233/? W/System.err:     at com.android.org.conscrypt.OpenSSLCipher.engineDoFinal(OpenSSLCipher.java:350)
08-30 18:31:16.712 4233-4233/? W/System.err:     at javax.crypto.Cipher.doFinal(Cipher.java:2056)
08-30 18:31:16.712 4233-4233/? W/System.err:     at ru.bullyboo.encoder.methods.AES.decrypt(AES.java:210)
08-30 18:31:16.712 4233-4233/? W/System.err:     at ru.bullyboo.encoder.builders.BuilderAES.decryption(BuilderAES.java:102)
08-30 18:31:16.712 4233-4233/? W/System.err:     at ru.bullyboo.encoder.builders.BaseBuilder.decrypt(BaseBuilder.java:226)
08-30 18:31:16.712 4233-4233/? W/System.err:     at com.zamil.ActBase.decrypt(ActBase.java:537)
08-30 18:31:16.712 4233-4233/? W/System.err:     at com.zamil.activity.ActLogin$5.onResponse(ActLogin.java:158)
08-30 18:31:16.712 4233-4233/? W/System.err:     at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)
08-30 18:31:16.712 4233-4233/? W/System.err:     at android.os.Handler.handleCallback(Handler.java:751)
08-30 18:31:16.712 4233-4233/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
08-30 18:31:16.712 4233-4233/? W/System.err:     at android.os.Looper.loop(Looper.java:154)
08-30 18:31:16.712 4233-4233/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6123)
08-30 18:31:16.712 4233-4233/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
08-30 18:31:16.712 4233-4233/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
08-30 18:31:16.712 4233-4233/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

**Comment by BullyBoo** [comment]
Yes, your mesage is not valid.
And the exception is not mine. It`s from jdk.

You can contact with in Telegram - @BullyBoo

**Comment by kmvora13990** [comment]
This is my message which i am decrypting : 
QSMUwnD8bJV2/0mkDPj5ri6J67tKr7cFlJcDk26MN1fDcEWMUDbtK8QT5swE8jz9p0hiLxkhU/Esxv2-mdADtKqMt2NytoUmJ3nOp7eOEhMWxjnbeaugKtGBo3WPIMLR

**Comment by BullyBoo** [comment]
I ll answer u after 20 minutes. I have dinner.

**Comment by kmvora13990** [comment]
its working now..thanks for your help..

**Comment by BullyBoo** [comment]
Do you understand what was wrong?

**Comment by kmvora13990** [comment]
yes..i understood

**Comment by BullyBoo** [comment]
Good luck!)

**Comment by kmvora13990** [comment]
Thank you...
